CREATE DATABASE abilitiestable;
USE abilitiestable;

CREATE TABLE ABILITIES
(
Ability_ID INT NOT NULL,
Ability_Name VARCHAR(20) NOT NULL,
Ability_Desc TINYTEXT NOT NULL,
PRIMARY KEY (Ability_ID)
);

INSERT INTO ABILITIES VALUES
(1, 'Adaptability', 'Powers up moves of the same type.'),
(2, 'Aerilate', 'Turns Normal-type moves into Flying-type moves.'),
(3, 'Aftermath', 'Damages the attacker landing the finishing hit.'),
(4, 'Air Lock', 'Eliminates the effects of weather.'),
(5, 'Analytic', 'Boosts move power when the Pokémon moves last.'),
(6, 'Anger Point', 'Maxes Attack after taking a critical hit.'),
(7, 'Anger Shell', 'Lowers Defense/Sp. Def and raises Attack/Sp. Atk/Speed when HP drops below half.'),
(8, 'Anticipation', 'Senses a foe''s dangerous moves.'),
(9, 'Arena Trap', 'Prevents the foe from fleeing.'),
(10, 'Armor Tai', 'Prevents opponent using priority moves.'),
(11, 'Aroma Veil', 'Protects allies from attacks that limit their move choices.'),
(12, 'As One', 'Combines Unnerve and Chilling Neigh/Grim Neigh'),
(13, 'Aura Break', 'Reduces power of Dark- and Fairy-type moves.'),
(14, 'Bad Dreams', 'Reduces a sleeping foe''s HP.'),
(15, 'Ball Fetch', 'Retrieves a Poké Ball from a failed throw.'),
(16, 'Battery', 'Raises power of teammates'' Special moves.'),
(17, 'Battle Armor', 'The Pokémon is protected against critical hits.'),
(18, 'Battle Bond', 'Transform into Ash-Greninja after causing opponent to faint.'),
(19, 'Beads of Ruin', 'Lowers Special Defense of all Pokémon except itself.'),
(20, 'Beast Boost', 'The Pokémon boosts its most proficient stat each time it knocks out a Pokémon.'),
(21, 'Berserk', 'Raises Special Attack when HP drops below half.'),
(22, 'Big Pecks', 'Protects the Pokémon from Defense-lowering attacks.'),
(23, 'Blaze', 'Powers up Fire-type moves in a pinch.'),
(24, 'Bulletproof', 'Protects the Pokémon from ball and bomb moves.'),
(25, 'Cheek Pouch', 'Restores additional HP when a Berry is consumed.'),
(26, 'Chilling Neigh', 'Boosts Attack after knocking out a Pokémon.'),
(27, 'Chlorophyll', 'Boosts the Pokémon''s Speed in sunshine.'),
(28, 'Clear Body', 'Prevents other Pokémon from lowering its stats.'),
(29, 'Cloud Nine', 'Eliminates the effects of weather.'),
(30, 'Color Change', 'Changes the Pokémon''s type to the foe''s move.'),
(31, 'Comatose', 'The Pokémon is always asleep but can still attack.'),
(32, 'Commander', 'Goes inside the mouth of an ally Dondozo if one is on the field.'),
(33, 'Competitive', 'Sharply raises Special Attack when the Pokémon''s stats are lowered.'),
(34, 'Compound Eyes', 'The Pokémon''s accuracy is boosted.'),
(35, 'Contrary', 'Makes stat changes have an opposite effect.'),
(36, 'Corrosion', 'The Pokémon can poison Steel and Poison types.'),
(37, 'Costar', 'Copies ally''s stat changes on entering battle.'),
(38, 'Cotton Down', 'Lowers foe''s Speed when hit.'),
(39, 'Cud Chew', 'Can eat the same Berry twice.'),
(40, 'Curious Medicine', 'Resets all stat changes upon entering battlefield.'),
(41, 'Cursed Body', 'May disable a move used on the Pokémon.'),
(42, 'Cute Charm', 'Contact with the Pokémon may cause infatuation.'),
(43, 'Damp', 'Prevents the use of self-destructing moves.'),
(44, 'Dancer', 'Copies the foe''s Dance moves.'),
(45, 'Dark Aura', 'Raises power of Dark type moves for all Pokémon in battle.'),
(46, 'Dauntless Sheild', 'Boosts Defense in battle.'),
(47, 'Dazzling', 'Protects the Pokémon from high-priority moves.'),
(48, 'Defeatist', 'Lowers stats when HP drops below half.'),
(49, 'Defiant', 'Sharply raises Attack when the Pokémon''s stats are lowered.'),
(50, 'Delta Stream', 'Creates strong winds when the ability activates.'),
(51, 'Desolate Land', 'Turns the sunlight extremely harsh when the ability activates.'),
(52, 'Disguise', 'Avoids damage for one turn.'),
(53, 'Download', 'Adjusts power according to a foe''s defenses.'),
(54, 'Dragon''s Maw', 'Powers up Dragon-type moves.'),
(55, 'Drizzle', 'The Pokémon makes it rain when it enters a battle.'),
(56, 'Drought', 'Turns the sunlight harsh when the Pokémon enters a battle.'),
(57, 'Dry Skin', 'Reduces HP if it is hot. Water restores HP.'),
(58, 'Early Bird', 'The Pokémon awakens quickly from sleep.'),
(59, 'Earth Eater', 'Restores HP when hit by a Ground-type move.'),
(60, 'Effect Spore', 'Contact may poison or cause paralysis or sleep.'),
(61, 'Electric Surge', 'The Pokémon creates an Electric Terrain when it enters a battle.'),
(62, 'Electromorphosis', 'Doubles power of the next Electric-type move when hit by an attack.'),
(63, 'Emobdy Aspect', 'Boosts Attack/Defense/Sp. Def/Speed depending on the form.'),
(64, 'Emercency Exit', 'Switches out when HP falls below 50%.'),
(65, 'Fairy Aura', 'Raises power of Fairy type moves for all Pokémon in battle.'),
(66, 'Filter', 'Reduces damage from super-effective attacks.'),
(67, 'Flame Body', 'Contact with the Pokémon may burn the attacker.'),
(68, 'Flare Boost', 'Powers up special attacks when burned.'),
(69, 'Flash Fire', 'It powers up Fire-type moves if it''s hit by one.'),
(70, 'Flower Gift', 'Powers up party Pokémon when it is sunny.'),
(71, 'Flower Veil', 'Prevents lowering of ally Grass-type Pokémon''s stats.'),
(72, 'Fluffy', 'Halves damage from contact moves, but doubles damage from Fire-type moves.'),
(73, 'Forecast', 'Castform transforms with the weather.'),
(74, 'Forewarn', 'Determines what moves a foe has.'),
(75, 'Friend Guard', 'Reduces damage done to allies.'),
(76, 'Frisk', 'The Pokémon can check a foe''s held item.'),
(77, 'Full Metal Body', 'Prevents other Pokémon from lowering its stats.'),
(78, 'Fur Coat', 'Reduces damage from physical moves.'),
(79, 'Gale Wings', 'Gives priority to Flying-type moves.'),
(80, 'Galvanize', 'Normal-type moves become Electric-type moves and their power boosted.'),
(81, 'Gluttony', 'Encourages the early use of a held Berry.'),
(82, 'Good as Gold', 'Gives immunity to status moves.'),
(83, 'Gooey', 'Contact with the Pokémon lowers the attacker''s Speed stat.'),
(84, 'Gorilla Tactics', 'Boosts the Pokémon''s Attack stat but only allows the use of the first selected move.'),
(85, 'Grass Pelt', 'Boosts the Defense stat in Grassy Terrain.'),
(86, 'Grassy Surge', 'The Pokémon creates a Grassy Terrain when it enters a battle.'),
(87, 'Grim Neigh', 'Boosts Special Attack after knocking out a Pokémon.'),
(88, 'Guard Dog', 'Boosts Attack if intimidated, and prevents being forced to switch out.'),
(89, 'Gulp Missile', 'Returns with a catch in its mouth after using Surf or Dive.'),
(90, 'Guts', 'Boosts Attack if there is a status problem.'),
(91, 'Hadron Engine', 'Creates an Electric Terrain when entering battle, and boosts Special Attack while active.'),
(92, 'Harvest', 'May create another Berry after one is used.'),
(93, 'Healer', 'May heal an ally''s status conditions.'),
(94, 'Heatproof', 'Weakens the power of Fire-type moves.'),
(95, 'Heavy Metal', 'Doubles the Pokémon''s weight.'),
(96, 'Honey Gather', 'The Pokémon may gather Honey from somewhere.'),
(97, 'Hospitality', 'Partially restores an ally''s HP when it enters a battle.'),
(98, 'Huge Power', 'Raises the Pokémon''s Attack stat.'),
(99, 'Hunger Switch', 'Changes forms each turn.'),
(100, 'Hustle', 'Boosts the Attack stat, but lowers accuracy.'),
(101, 'Hydration', 'Heals status problems if it is raining.'),
(102, 'Hyper Cutter', 'Prevents other Pokémon from lowering Attack stat.'),
(103, 'Ice Body', 'The Pokémon gradually regains HP in a hailstorm.'),
(104, 'Ice Face', 'Avoids damage from Physical moves for one turn.'),
(105, 'Ice Scales', 'Halves damage from Special moves.'),
(106, 'Illuminate', 'Raises the likelihood of meeting wild Pokémon.'),
(107, 'Illusion', 'Enters battle disguised as the last Pokémon in the party.'),
(108, 'Immunity', 'Prevents the Pokémon from getting poisoned.'),
(109, 'Imposter', 'It transforms itself into the Pokémon it is facing.'),
(110, 'Infiltrator', 'Passes through the foe''s barrier and strikes.'),
(111, 'Innards Out', 'Deals damage upon fainting.'),
(112, 'Inner Focus', 'The Pokémon is protected from flinching.'),
(113, 'Insomnia', 'Prevents the Pokémon from falling asleep.'),
(114, 'Intimidate', 'Lowers the foe''s Attack stat.'),
(115, 'Intrepid Sword', 'Boosts Attack in battle.'),
(116, 'Iron Barbs', 'Inflicts damage to the Pokémon on contact.'),
(117, 'Iron Fist', 'Boosts the power of punching moves.'),
(118, 'Justified', 'Raises Attack when hit by a Dark-type move.'),
(119, 'Keen Eye', 'Prevents other Pokémon from lowering accuracy.'),
(120, 'Klutz', 'The Pokémon can''t use any held items.'),
(121, 'Leaf Guard', 'Prevents problems with status in sunny weather.'),
(122, 'Levitate', 'Gives immunity to Ground type moves.'),
(123, 'Libero', 'Changes the Pokémon''s type to its last used move.'),
(124, 'Light Metal', 'Halves the Pokémon''s weight.'),
(125, 'Lightning Rod', 'Draws in all Electric-type moves to up Sp. Attack.'),
(126, 'Limber', 'The Pokémon is protected from paralysis.'),
(127, 'Lingering Aroma', 'Contact changes the attacker''s Ability to Lingering Aroma.'),
(128, 'Liquid Ooze', 'Damages attackers using any draining move.'),
(129, 'Liquid Voice', 'All sound-based moves become Water-type moves.'),
(130, 'Long Reach', 'The Pokémon uses its moves without making contact with the target.'),
(131, 'Magic Bounce', 'Reflects status- changing moves.'),
(132, 'Magic Guard', 'Protects the Pokémon from indirect damage.'),
(133, 'Magician', 'The Pokémon steals the held item of a Pokémon it hits with a move.'),
(134, 'Magma Armor', 'Prevents the Pokémon from becoming frozen.'),
(135, 'Magnet Pull', 'Prevents Steel-type Pokémon from escaping.'),
(136, 'Marvel Scale', 'Ups Defense if there is a status problem.'),
(137, 'Mega Launcher', 'Boosts the power of aura and pulse moves.'),
(138, 'Merciless', 'The Pokémon''s attacks become critical hits if the target is poisoned.'),
(139, 'Mimicry', 'Changes type depending on the terrain.'),
(140, 'Mind''s Eye', 'Ignores opponent''s Evasiveness, and allows Normal- and Fighting-type attacks to hit Ghosts.'),
(141, 'Minus', 'Ups Sp. Atk if another Pokémon has Plus or Minus.'),
(142, 'Mirror Armor', 'Reflects any stat-lowering effects.'),
(143, 'Misty Surge', 'The Pokémon creates a Misty Terrain when it enters a battle.'),
(144, 'Mold Breaker', 'Moves can be used regardless of Abilities.'),
(145, 'Moody', 'Raises one stat and lowers another.'),
(146, 'Motor Drive', 'Raises Speed if hit by an Electric-type move.'),
(147, 'Moxie', 'Boosts Attack after knocking out any Pokémon.'),
(148, 'Multiscale', 'Reduces damage when HP is full.'),
(149, 'Multitype', 'Changes type to match the held Plate.'),
(150, 'Mummy', 'Contact with this Pokémon spreads this Ability.'),
(151, 'Mycelium Might', 'Status moves go last, but are not affected by the opponent''s ability.'),
(152, 'Natural Cure', 'All status problems heal when it switches out.'),
(153, 'Neuroforce', 'Powers up moves that are super effective.'),
(154, 'Neutralizing Gas', 'Neutralizes abilities of all Pokémon in battle.'),
(155, 'No Guard', 'Ensures attacks by or against the Pokémon land.'),
(156, 'Normalize', 'All the Pokémon''s moves become the Normal type.'),
(157, 'Oblivious', 'Prevents it from becoming infatuated.'),
(158, 'Opportunist', 'Copies stat boosts by the opponent.'),
(159, 'Orichalcum Pulse', 'Turns the sunlight harsh when entering battle, and boosts Attack while active.'),
(160, 'Overcoat', 'Protects the Pokémon from weather damage.'),
(161, 'Overgrow', 'Powers up Grass-type moves in a pinch.'),
(162, 'Own Tempo', 'Prevents the Pokémon from becoming confused.'),
(163, 'Parental Bond', 'Allows the Pokémon to attack twice.'),
(164, 'Pastel Veil', 'Prevents the Pokémon and its allies from being poisoned.'),
(165, 'Perish Body', 'When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle.'),
(166, 'Pickpocket', 'Steals an item when hit by another Pokémon.'),
(167, 'Pickup', 'The Pokémon may pick up items.'),
(168, 'Pixilate', 'Turns Normal-type moves into Fairy-type moves.'),
(169, 'Plus', 'Ups Sp. Atk if another Pokémon has Plus or Minus.'),
(170, 'Poison Heal', 'Restores HP if the Pokémon is poisoned.'),
(171, 'Poison Point', 'Contact with the Pokémon may poison the attacker.'),
(172, 'Poison Puppeteer', 'Poisoned Pokémon also become confused.'),
(173, 'Poison Touch', 'May poison targets when a Pokémon makes contact.'),
(174, 'Power Construct', 'Changes form when HP drops below half.'),
(175, 'Power of Alchemy', 'The Pokémon copies the Ability of a defeated ally.'),
(176, 'Power Spot', 'Just being next to the Pokémon powers up moves.'),
(177, 'Prankster', 'Gives priority to a status move.'),
(178, 'Pressure', 'The Pokémon raises the foe''s PP usage.'),
(179, 'Primordial Sea', 'Makes it rain heavily when the ability activates.'),
(180, 'Prism Armor', 'Reduces damage from super-effective attacks.'),
(181, 'Propeller Tail', 'Ignores moves and abilities that draw in moves.'),
(182, 'Protean', 'Changes the Pokémon''s type to its last used move.'),
(183, 'Protosynthesis', 'Raises highest stat in harsh sunlight, or if holding Booster Energy.'),
(184, 'Psychic Surge', 'The Pokémon creates a Psychic Terrain when it enters a battle.'),
(185, 'Punk Rock', 'Boosts sound-based moves and halves damage from the same moves.'),
(186, 'Pure Power', 'Raises the Pokémon''s Attack stat.'),
(187, 'Purifying Salt', 'Protects from status conditions and halves damage from Ghost-type moves.'),
(188, 'Quark Drive', 'Raises highest stat on Electric Terrain, or if holding Booster Energy.'),
(189, 'Queenly Majesty', 'Prevents use of priority moves.'),
(190, 'Quick Draw', 'Enables the Pokémon to move first occasionally.'),
(191, 'Quick Feet', 'Boosts Speed if there is a status problem.'),
(192, 'Rain Dish', 'The Pokémon gradually regains HP in rain.'),
(193, 'Rattled', 'Bug, Ghost or Dark type moves scare it and boost its Speed.'),
(194, 'Receiver', 'Inherits an ally''s ability when it faints.'),
(195, 'Reckless', 'Powers up moves that have recoil damage.'),
(196, 'Refrigerate', 'Turns Normal-type moves into Ice-type moves.'),
(197, 'Regenerator', 'Restores a little HP when withdrawn from battle.'),
(198, 'Ripen', 'Doubles the effect of berries.'),
(199, 'Rivalry', 'Deals more damage to a Pokémon of same gender.'),
(200, 'RKS System', 'Changes type depending on held item.'),
(201, 'Rock Head', 'Protects the Pokémon from recoil damage.'),
(202, 'Rocky Payload', 'Powers up Rock-type moves.'),
(203, 'Rough Skin', 'Inflicts damage to the attacker on contact.'),
(204, 'Run Away', 'Enables a sure getaway from wild Pokémon.'),
(205, 'Sand Force', 'Boosts certain moves'' power in a sandstorm.'),
(206, 'Sand Rush', 'Boosts the Pokémon''s Speed in a sandstorm.'),
(207, 'Sand Spit', 'Creates a sandstorm when hit by an attack.'),
(208, 'Sand Stream', 'The Pokémon summons a sandstorm in battle.'),
(209, 'Sand Veil', 'Boosts the Pokémon''s evasion in a sandstorm.'),
(210, 'Sap Sipper', 'Boosts Attack when hit by a Grass-type move.'),
(211, 'Schooling', 'Changes Wishiwashi to School Form.'),
(212, 'Scrappy', 'Enables moves to hit Ghost-type Pokémon.'),
(213, 'Screen Cleaner', 'Nullifies effects of Light Screen, Reflect, and Aurora Veil.'),
(214, 'Seed Sower', 'Turns the ground into Grassy Terrain when the Pokémon is hit by an attack.'),
(215, 'Serene Grace', 'Boosts the likelihood of added effects appearing.'),
(216, 'Shadow Shield', 'Reduces damage when HP is full.'),
(217, 'Shadow Tag', 'Prevents the foe from escaping.'),
(218, 'Sharpness', 'Boosts the power of slicing moves.'),
(219, 'Shed Skin', 'The Pokémon may heal its own status problems.'),
(220, 'Sheer Force', 'Removes added effects to increase move damage.'),
(221, 'Shell Armor', 'The Pokémon is protected against critical hits.'),
(222, 'Shield Dust', 'Blocks the added effects of attacks taken.'),
(223, 'Shields Down', 'Changes stats when HP drops below half.'),
(224, 'Simple', 'Doubles all stat changes.'),
(225, 'Skill Link', 'Increases the frequency of multi-strike moves.'),
(226, 'Slow Start', 'Temporarily halves Attack and Speed.'),
(227, 'Slush Rush', 'Boosts the Pokémon''s Speed stat in a hailstorm.'),
(228, 'Sniper', 'Powers up moves if they become critical hits.'),
(229, 'Snow Cloak', 'Raises evasion in a hailstorm.'),
(230, 'Snow Warning', 'The Pokémon summons a hailstorm in battle.'),
(231, 'Solar Power', 'In sunshine, Sp. Atk is boosted but HP decreases.'),
(232, 'Solid Rock', 'Reduces damage from super-effective attacks.'),
(233, 'Soul-Heart', 'Raises Special Attack when another Pokémon faints.'),
(234, 'Soundproof', 'Gives immunity to sound-based moves.'),
(235, 'Speed Boost', 'Its Speed stat is gradually boosted.'),
(236, 'Stakeout', 'Deals double damage to Pokémon switching in.'),
(237, 'Stall', 'The Pokémon moves after all other Pokémon do.'),
(238, 'Stalwart', 'Ignores moves and abilities that draw in moves.'),
(239, 'Stamina', 'Raises Defense when attacked.'),
(240, 'Stance Change', 'Changes form depending on moves used.'),
(241, 'Static', 'Contact with the Pokémon may cause paralysis.'),
(242, 'Steadfast', 'Raises Speed each time the Pokémon flinches.'),
(243, 'Steam Engine', 'Drastically raises Speed when hit by a Fire- or Water-type move.'),
(244, 'Steelworker', 'Powers up Steel-type moves.'),
(245, 'Steely Spirit', 'Powers up ally Pokémon''s Steel-type moves.'),
(246, 'Stench', 'The stench may cause the target to flinch.'),
(247, 'Sticky Hold', 'Protects the Pokémon from item theft.'),
(248, 'Storm Drain', 'Draws in all Water-type moves to up Sp. Attack.'),
(249, 'Strong Jaw', 'Boosts the power of biting moves.'),
(250, 'Sturdy', 'It cannot be knocked out with one hit.'),
(251, 'Suction Cups', 'Negates all moves that force switching out.'),
(252, 'Super Luck', 'Heightens the critical-hit ratios of moves.'),
(253, 'Supersweet Syrup', 'Lowers opponent''s Evasiveness when entering battle.'),
(254, 'Supreme Overload', 'Attack and Special Attack are boosted for each party Pokémon that has been defeated.'),
(255, 'Surge Surfer', 'Doubles Speed during Electric Terrain.'),
(256, 'Swarm', 'Powers up Bug-type moves in a pinch.'),
(257, 'Sweet Veil', 'Prevents the Pokémon and allies from falling asleep.'),
(258, 'Swift Swim', 'Boosts the Pokémon''s Speed in rain.'),
(259, 'Sword of Ruin', 'Lowers Defense of all Pokémon except itself.'),
(260, 'Symbiosis', 'The Pokémon can pass an item to an ally.'),
(261, 'Synchronize', 'Passes a burn, poison, or paralysis to the foe.'),
(262, 'Tablets of Ruin', 'Lowers Attack of all Pokémon except itself.'),
(263, 'Tangled Feet', 'Raises evasion if the Pokémon is confused.'),
(264, 'Tangling Hair', 'Contact with the Pokémon lowers the attacker''s Speed stat.'),
(265, 'Technician', 'Powers up the Pokémon''s weaker moves.'),
(266, 'Telepathy', 'Anticipates an ally''s attack and dodges it.'),
(267, 'Tera Shell', 'Moves are not very effective when HP is full.'),
(268, 'Tera Shift', 'Transforms into Terastal Form in battle.'),
(269, 'Teraform Zero', 'Eliminates all effects of weather and terrain.'),
(270, 'Teravolt', 'Moves can be used regardless of Abilities.'),
(271, 'Thermal Exchange', 'Raises Attack when hit by a Fire-type move. Cannot be burned.'),
(272, 'Thick Fat', 'Ups resistance to Fire- and Ice-type moves.'),
(273, 'Tinted Lens', 'Powers up “not very effective” moves.'),
(274, 'Torrent', 'Powers up Water-type moves in a pinch.'),
(275, 'Tough Claws', 'Boosts the power of contact moves.'),
(276, 'Toxic Boost', 'Powers up physical attacks when poisoned.'),
(277, 'Toxic Chain', 'May cause bad poisoning.'),
(278, 'Toxis Debris', 'Scatters poison spikes at the feet of the opposing team when the Pokémon takes damage from physical moves.'),
(279, 'Trace', 'The Pokémon copies a foe''s Ability.'),
(280, 'Transistor', 'Powers up Electric-type moves.'),
(281, 'Triage', 'Gives priority to restorative moves.'),
(282, 'Truant', 'Pokémon can''t attack on consecutive turns.'),
(283, 'Turboblaze', 'Moves can be used regardless of Abilities.'),
(284, 'Unaware', 'Ignores any stat changes in the Pokémon.'),
(285, 'Unburden', 'Raises Speed if a held item is used.'),
(286, 'Unnerve', 'Makes the foe nervous and unable to eat Berries.'),
(287, 'Unseen Fist', 'Contact moves can strike through Protect/Detect.'),
(288, 'Vessel of Ruin', 'Lowers Special Attack of all Pokémon except itself.'),
(289, 'Victory Star', 'Boosts the accuracy of its allies and itself.'),
(290, 'Vital Spirit', 'Prevents the Pokémon from falling asleep.'),
(291, 'Volt Absorb', 'Restores HP if hit by an Electric-type move.'),
(292, 'Wandering Spirit', 'Swaps abilities with opponents on contact.'),
(293, 'Water Absorb', 'Restores HP if hit by a Water-type move.'),
(294, 'Water Bubble', 'Halves damage from Fire-type moves, doubles power of Water-type moves used, and prevents burns.'),
(295, 'Water Compaction', 'Sharply raises Defense when hit by a Water-type move.'),
(296, 'Water Veil', 'Prevents the Pokémon from getting a burn.'),
(297, 'Weak Armor', 'Physical attacks lower Defense and raise Speed.'),
(298, 'Well-Baked Body', 'Immune to Fire-type moves, and Defense is sharply boosted.'),
(299, 'White Smoke', 'Prevents other Pokémon from lowering its stats.'),
(300, 'Wimp Out', 'Switches out when HP drops below half.'),
(301, 'Wind Power', 'Doubles power of the next Electric-type move used, when hit by a wind move.'),
(302, 'Wind Rider', 'Takes no damage from wind moves, and boosts Attack if hit by one.'),
(303, 'Wonder Guard', 'Only supereffective moves will hit.'),
(304, 'Wonder Skin', 'Makes status-changing moves more likely to miss.'),
(305, 'Zen Mode', 'Changes form when HP drops below half.'),
(306, 'Zero to Hero', 'Transforms into its Hero Form when switching out.');